
project_id = "laoltiyaaagiiutahypb"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://dde3f2f4-d22c-4d88-81b1-a276fad88405.lovableproject.com"]
jwt_expiry = 3600
enable_signup = true
enable_email_confirmations = false
enable_sms_confirmations = false

[db]
port = 54322

[edge_functions]
enabled = true
port = 54323

[functions.stripe-webhook]
verify_jwt = false

[functions.payout-commissions]
verify_jwt = false

[functions.convert-earnings-to-btc]
verify_jwt = false

[functions.commission-payout-coinbase]
verify_jwt = false

[functions.create-subscription-checkout]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[rest]
enabled = true
port = 54321
